// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yadeh.Infrastructure.Persistence;

#nullable disable

namespace Yadeh.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YadehDbContext))]
    [Migration("20260912210223_InitialConversationLibrary")]
    partial class InitialConversationLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Yadeh.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationSnapshotId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationMessages_Sequence", "\"Sequence\" >= 0");
                        });
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.ConversationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl");

                    b.HasIndex("ConversationId", "ImportedAtUtc");

                    b.ToTable("ConversationSnapshots", (string)null);
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.ConversationMessage", b =>
                {
                    b.HasOne("Yadeh.Domain.Conversations.ConversationSnapshot", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.ConversationSnapshot", b =>
                {
                    b.HasOne("Yadeh.Domain.Conversations.Conversation", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.Conversation", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Yadeh.Domain.Conversations.ConversationSnapshot", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
